from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Flight(Base):
    __tablename__ = 'flights'

    id = Column(Integer, primary_key=True, index=True)
    ident = Column(String, nullable=True)
    ident_icao = Column(String, nullable=True)
    ident_iata = Column(String, nullable=True)
    actual_runway_off = Column(String, nullable=True)
    actual_runway_on = Column(String, nullable=True)
    fa_flight_id = Column(String, nullable=True)
    operator = Column(String, nullable=True)
    operator_icao = Column(String, nullable=True)
    operator_iata = Column(String, nullable=True)
    flight_number = Column(String, nullable=True)
    registration = Column(String, nullable=True)
    atc_ident = Column(String, nullable=True)
    inbound_fa_flight_id = Column(String, nullable=True)
    codeshares = Column(String, nullable=True)  # Serialize list as JSON or use another format
    codeshares_iata = Column(String, nullable=True)  # Serialize list as JSON or use another format
    blocked = Column(Boolean, nullable=True)
    diverted = Column(Boolean, nullable=True)
    cancelled = Column(Boolean, nullable=True)
    position_only = Column(Boolean, nullable=True)
    
    # Origin fields
    origin_code = Column(String, nullable=True)
    origin_code_icao = Column(String, nullable=True)
    origin_code_iata = Column(String, nullable=True)
    origin_code_lid = Column(String, nullable=True)
    origin_timezone = Column(String, nullable=True)
    origin_name = Column(String, nullable=True)
    origin_city = Column(String, nullable=True)
    origin_airport_info_url = Column(String, nullable=True)
    
    # Destination fields
    destination_code = Column(String, nullable=True)
    destination_code_icao = Column(String, nullable=True)
    destination_code_iata = Column(String, nullable=True)
    destination_code_lid = Column(String, nullable=True)
    destination_timezone = Column(String, nullable=True)
    destination_name = Column(String, nullable=True)
    destination_city = Column(String, nullable=True)
    destination_airport_info_url = Column(String, nullable=True)
    
    departure_delay = Column(Float, nullable=True)
    arrival_delay = Column(Float, nullable=True)
    filed_ete = Column(Float, nullable=True)
    progress_percent = Column(Float, nullable=True)
    status = Column(String, nullable=True)
    aircraft_type = Column(String, nullable=True)
    route_distance = Column(Float, nullable=True)
    filed_airspeed = Column(Float, nullable=True)
    filed_altitude = Column(Float, nullable=True)
    route = Column(String, nullable=True)
    baggage_claim = Column(String, nullable=True)
    seats_cabin_business = Column(Integer, nullable=True)
    seats_cabin_coach = Column(Integer, nullable=True)
    seats_cabin_first = Column(Integer, nullable=True)
    gate_origin = Column(String, nullable=True)
    gate_destination = Column(String, nullable=True)
    terminal_origin = Column(String, nullable=True)
    terminal_destination = Column(String, nullable=True)
    type = Column(String, nullable=True)
    scheduled_out = Column(DateTime, nullable=True)
    estimated_out = Column(DateTime, nullable=True)
    actual_out = Column(DateTime, nullable=True)
    scheduled_off = Column(DateTime, nullable=True)
    estimated_off = Column(DateTime, nullable=True)
    actual_off = Column(DateTime, nullable=True)
    scheduled_on = Column(DateTime, nullable=True)
    estimated_on = Column(DateTime, nullable=True)
    actual_on = Column(DateTime, nullable=True)
    scheduled_in = Column(DateTime, nullable=True)
    estimated_in = Column(DateTime, nullable=True)
    actual_in = Column(DateTime, nullable=True)
    foresight_predictions_available = Column(Boolean, nullable=True)
